# Generated by Django 5.2.3 on 2025-06-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users_wishlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlists',
            new_name='wishlist',
        ),
    ]
